name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app (vite)
        run: npm run build

  deploy:
    name: Deploy to Vercel (prod)
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Link by NAME + SCOPE (avoids brittle IDs)
      - name: Link Vercel project
        run: vercel link --yes --project "${{ secrets.VERCEL_PROJECT_NAME }}" --scope "${{ secrets.VERCEL_SCOPE }}" --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Pull Vercel env (production)
        run: vercel pull --yes --environment=production --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Build with Vercel (prebuilt output)
        run: vercel build --prod --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy prebuilt output to Vercel
        run: vercel deploy --prebuilt --prod --token "${{ secrets.VERCEL_TOKEN }}"
